version: '3.8'

services:
  ffc-sfi-agreement-api:
    build:
      context: .
      target: production
    image: ffc-sfi-agreement-api
    container_name: ffc-sfi-agreement-api
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfi-agreement-api-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
