version: '3.8'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-sfi-agreement-api:
    build:
      target: development
    image: ffc-sfi-agreement-api-development
    container_name: ffc-sfi-agreement-api-development
    ports:
      - "3009:3009"
      - "9239:9229"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
