version: '3.8'

services:
  ffc-sfi-agreement-api:
    build:
      context: .
      target: production
    image: ffc-sfi-agreement-api
    depends_on:
      - ffc-sfi-agreement-api-postgres
    container_name: ffc-sfi-agreement-api
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfi-agreement-api-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      POSTGRES_DB: ffc_sfi_agreement_api
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-sfi-agreement-api-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
  
  ffc-sfi-agreement-api-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_sfi_agreement_api
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
