environment: development
name: ffc-sfi-agreement-api
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-agreement-api

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-sfi-agreement-api-config-map

containerSecret:
  name: ffc-sfi-agreement-api-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3009

livenessProbe:
  path: /healthz
  port: 3009
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3009
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
